// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDw4vfQM5pTfJnx_Dw-zaJvz2V6IudqE',
    appId: '1:228815587191:web:8d2bc7c9b6682939430372',
    messagingSenderId: '228815587191',
    projectId: 'butterfly-counts',
    authDomain: 'butterfly-counts.firebaseapp.com',
    storageBucket: 'butterfly-counts.firebasestorage.app',
    measurementId: 'G-TSJ2ETNEZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAvDuywQHMt2J21LHVTaLu9UEAFbQc1Ck',
    appId: '1:228815587191:android:1bc3c1ee848a40ea430372',
    messagingSenderId: '228815587191',
    projectId: 'butterfly-counts',
    storageBucket: 'butterfly-counts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEBRQNrvsQk9W5MxX0VQj8SstP-i0ULg',
    appId: '1:228815587191:ios:e2d10ab1dc7d29b9430372',
    messagingSenderId: '228815587191',
    projectId: 'butterfly-counts',
    storageBucket: 'butterfly-counts.firebasestorage.app',
    iosBundleId: 'in.bigbutterflymonth.butterflyCount',
  );
}