// lib/data/models/count_model.dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:butterfly_counts/data/models/observation.dart'; // Import Observation model

part 'count_model.g.dart';

@JsonSerializable()
class CountModel {
  final int? id;
  @JsonKey(name: 'user_id')
  final String userId;
  final String? team;
  @JsonKey(name: 'open_access')
  final bool openAccess;
  // Use @JsonKey for date/time formatting if you want json_serializable to handle it,
  // otherwise, manually format in toJson as you currently do.
  // For simplicity, we'll keep manual formatting in toJson for now.
  final DateTime date;
  @JsonKey(name: 'start_time')
  final DateTime? startTime;
  @JsonKey(name: 'end_time')
  final DateTime? endTime;
  final double latitude;
  final double longitude;
  final double? altitude;
  final double? accuracy;
  @JsonKey(name: 'place_name')
  final String? placeName;
  @JsonKey(name: 'district_id')
  final String? districtId;
  @JsonKey(name: 'district_name')
  final String? districtName;
  @JsonKey(name: 'state_name')
  final String? stateName;
  @JsonKey(name: 'country_name')
  final String? countryName;
  @JsonKey(name: 'distance_covered')
  final double? distanceCovered;
  final String? weather;
  final String? notes;
  final String? version;
  @JsonKey(name: 'created_at')
  final DateTime? createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime? updatedAt;

  // NEW: Add observations list - json_serializable will handle this automatically
  final List<Observation> observations;

  CountModel({
    this.id,
    required this.userId,
    this.team,
    required this.openAccess,
    required this.date,
    this.startTime,
    this.endTime,
    required this.latitude,
    required this.longitude,
    this.altitude,
    this.accuracy,
    this.placeName,
    this.districtId,
    this.districtName,
    this.stateName,
    this.countryName,
    this.distanceCovered,
    this.weather,
    this.notes,
    this.version,
    this.createdAt,
    this.updatedAt,
    required this.observations, // This is the required parameter
  });

  // Factory constructor for deserialization from JSON.
  // This will be generated by build_runner.
  // json_serializable will automatically call Observation.fromJson for each item in the 'observations' list.
  factory CountModel.fromJson(Map<String, dynamic> json) =>
      _$CountModelFromJson(json);

  // MODIFIED: toJson to include observations and custom date formatting
  @override
  Map<String, dynamic> toJson() {
    // Generate the base JSON from JsonSerializable
    final Map<String, dynamic> json = _$CountModelToJson(this);

    // Manually format dates for Laravel's expected format, overriding generated values
    json['date'] = DateFormat('yyyy-MM-dd HH:mm:ss').format(date);
    json['start_time'] = startTime != null
        ? DateFormat('yyyy-MM-dd HH:mm:ss').format(startTime!)
        : null;
    json['end_time'] = endTime != null
        ? DateFormat('yyyy-MM-dd HH:mm:ss').format(endTime!)
        : null;

    // The 'observations' list will already be serialized by _$CountModelToJson
    // because Observation is also JsonSerializable.
    // No need for: json['observations'] = observations.map((obs) => obs.toJson()).toList();
    // unless you need custom serialization for observations here.

    return json;
  }
}
