// lib/data/models/count_model.dart
import 'package:flutter/material.dart'; // For @required if using older Dart, or just for clarity
import 'package:intl/intl.dart'; // For date formatting
import 'package:json_annotation/json_annotation.dart'; // New import for JsonSerializable

part 'count_model.g.dart'; // This line tells Dart to look for the generated file

@JsonSerializable() // Add this annotation above your class
class CountModel {
  final int? id; // Null for new counts, will be set by backend
  @JsonKey(
    name: 'user_id',
  ) // Map JSON key to Dart field name (snake_case to camelCase)
  final String userId;
  final String? team;
  @JsonKey(name: 'open_access')
  final bool openAccess;
  final DateTime date;
  @JsonKey(name: 'start_time')
  final DateTime? startTime;
  @JsonKey(name: 'end_time')
  final DateTime? endTime;
  final double latitude;
  final double longitude;
  final double? altitude;
  final double? accuracy;
  @JsonKey(name: 'place_name')
  final String? placeName;
  @JsonKey(name: 'district_id')
  final String? districtId; // Populated by backend
  @JsonKey(name: 'district_name')
  final String? districtName; // Populated by backend
  @JsonKey(name: 'state_name')
  final String? stateName; // Populated by backend
  @JsonKey(name: 'country_name')
  final String? countryName; // Populated by backend
  @JsonKey(name: 'distance_covered')
  final double? distanceCovered;
  final String? weather;
  final String? notes; // Corresponds to 'comments' in your UI
  final String? version;
  @JsonKey(name: 'created_at')
  final DateTime? createdAt; // Set by backend
  @JsonKey(name: 'updated_at')
  final DateTime? updatedAt; // Set by backend

  CountModel({
    this.id,
    required this.userId,
    this.team,
    required this.openAccess,
    required this.date,
    this.startTime,
    this.endTime,
    required this.latitude,
    required this.longitude,
    this.altitude,
    this.accuracy,
    this.placeName,
    this.districtId,
    this.districtName,
    this.stateName,
    this.countryName,
    this.distanceCovered,
    this.weather,
    this.notes,
    this.version,
    this.createdAt,
    this.updatedAt,
  });

  /// Factory constructor for deserialization from JSON.
  /// This will be generated by build_runner.
  factory CountModel.fromJson(Map<String, dynamic> json) =>
      _$CountModelFromJson(json);

  /// Method for serialization to JSON.
  /// This will be generated by build_runner.
  Map<String, dynamic> toJson() => _$CountModelToJson(this);
}
